"""Add Sharpe governance and external figures to the statistical notebook.

The update is anchor-based and idempotent so it preserves unrelated notebook
cells and the user's existing outputs while making the requested additions.
"""

from __future__ import annotations

from pathlib import Path

import nbformat


PROJECT_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_PATH = PROJECT_ROOT / "notebooks" / "exploration" / "statistical_feature_research.ipynb"


def _source(cell: nbformat.NotebookNode) -> str:
    return str(cell.get("source", ""))


def _find_unique_cell(notebook: nbformat.NotebookNode, token: str) -> int:
    matches = [index for index, cell in enumerate(notebook.cells) if token in _source(cell)]
    if len(matches) != 1:
        raise RuntimeError(f"Expected one notebook cell containing {token!r}; found {matches}")
    return matches[0]


def _append_once(
    notebook: nbformat.NotebookNode,
    *,
    anchor: str,
    marker: str,
    text: str,
) -> None:
    index = _find_unique_cell(notebook, anchor)
    source = _source(notebook.cells[index])
    if marker not in source:
        notebook.cells[index].source = source.rstrip() + "\n\n" + text.strip() + "\n"


def _insert_after_once(
    notebook: nbformat.NotebookNode,
    *,
    anchor: str,
    marker: str,
    cells: list[nbformat.NotebookNode],
) -> None:
    if any(marker in _source(cell) for cell in notebook.cells):
        return
    index = _find_unique_cell(notebook, anchor)
    notebook.cells[index + 1 : index + 1] = cells


def _replace_once(
    notebook: nbformat.NotebookNode,
    *,
    anchor: str,
    old: str,
    new: str,
) -> None:
    index = _find_unique_cell(notebook, anchor)
    source = _source(notebook.cells[index])
    if new in source:
        return
    if old not in source:
        raise RuntimeError(f"Cell containing {anchor!r} does not contain replacement target {old!r}")
    notebook.cells[index].source = source.replace(old, new, 1)


def update_notebook(notebook: nbformat.NotebookNode) -> None:
    _append_once(
        notebook,
        anchor="# Statistical Feature Research",
        marker="reports/figures/statistical_feature_research",
        text="""
All visual diagnostics generated by this notebook are saved outside the notebook under
`reports/figures/statistical_feature_research`; figures are closed after saving so the
executed notebook remains an auditable calculation record rather than an embedded image archive.
""",
    )

    _insert_after_once(
        notebook,
        anchor="Random seed fixed at",
        marker="## 1.5 Sharpe-Ratio Governance",
        cells=[
            nbformat.v4.new_markdown_cell(
                """## 1.5 Sharpe-Ratio Governance

Sharpe is used only when a research object can be represented as an honest time-indexed return stream. The annualization convention is `sqrt(252)`, volatility is the sample standard deviation (`ddof=1`), and the per-day risk-free return is zero because the notebook reports dimensionless R or tick spreads rather than capital returns.

Two uses are valid here. Section 7 reports a **feature-spread Sharpe diagnostic**: Development-fitted quintile edges and Development-fitted directional orientation create equal-date-weighted top-versus-bottom forward-return spreads, then the unchanged mapping is evaluated on Validation. This is secondary screening evidence, not executable PnL, because event returns overlap and costs are absent. Section 11 reports the **strategy Sharpe** of sequential daily net R, including zero-trade eligible dates and explicit frictionless, base, and pessimistic cost scenarios. Sharpe does not retroactively change any frozen advancement criterion.
"""
            )
        ],
    )

    _append_once(
        notebook,
        anchor="## 5.1 Baseline Scope, Metrics, and Comparison Rules",
        marker="Sharpe is intentionally not computed in Section 5",
        text="""
Sharpe is intentionally not computed in Section 5. These are overlapping, unconditional event labels with no direction, position schedule, or cost model; annualizing them would manufacture a strategy interpretation that the baseline does not possess.
""",
    )
    _append_once(
        notebook,
        anchor="## 6.1 Research Contract, Scope, and Leakage Boundary",
        marker="Sharpe is not a feature-engineering metric",
        text="""
Sharpe is not a feature-engineering metric: a predictor has no return until direction, portfolio formation, holding period, and costs are specified. Section 6 therefore retains coverage, leakage, numerical, boundary, and reproducibility diagnostics; the first risk-adjusted feature comparison appears only in Section 7.
""",
    )
    _append_once(
        notebook,
        anchor="# 7.0 Univariate Feature Evaluation",
        marker="feature-spread Sharpe",
        text="""
As a secondary economic diagnostic, every evaluated engineered feature is also mapped to a daily directional feature spread. Orientation and bucket boundaries are fitted on Development only and reused unchanged on Validation. The resulting feature-spread Sharpe is never used as standalone evidence of a tradable strategy and does not alter the frozen IC-based shortlist gates.
""",
    )
    _append_once(
        notebook,
        anchor="# 8.0 Redundancy and Incremental Information",
        marker="Sharpe is not recomputed in Section 8",
        text="""
Sharpe is not recomputed in Section 8 because partial rank IC and correlation clusters describe incremental information, not a new return stream. Section 7's spread diagnostics remain available for comparison without becoming a clustering or advancement input.
""",
    )
    _append_once(
        notebook,
        anchor="# 9.0 Multivariate Research",
        marker="Sharpe is inappropriate for the Section 9 target",
        text="""
Sharpe is inappropriate for the Section 9 target: the model predicts unsigned future range rather than signed returns. Daily IC, paired IC improvement, AUC, Brier score, and calibration directly evaluate that forecasting task; a Sharpe label here would incorrectly present volatility opportunity as PnL.
""",
    )
    _append_once(
        notebook,
        anchor="# 10.0 Statistical Signal Construction",
        marker="Sharpe remains deferred in Section 10",
        text="""
Sharpe remains deferred in Section 10. Candidate rules now exist, but no realized sequential return stream exists until Section 11 applies position exclusivity, exits, and transaction-cost assumptions.
""",
    )
    _append_once(
        notebook,
        anchor="# 11.0 Independent Sequential Backtest",
        marker="This is the notebook's primary valid Sharpe application",
        text="""
This is the notebook's primary valid Sharpe application. Trades are aggregated to daily net R, every eligible trading date is retained (including zero-trade dates), and Sharpe is reported separately by variant, partition, and cost scenario. It is a performance diagnostic alongside expectancy, profit factor, and drawdown; the predeclared advancement rule remains positive base-cost expectancy in both partitions.
""",
    )
    _append_once(
        notebook,
        anchor="# 12.0 Hybrid Integration Research",
        marker="Sharpe is not assigned to Section 12",
        text="""
Sharpe is not assigned to Section 12 because the robust-R events overlap and do not form a sequential portfolio return series. Date-block improvement intervals, event/date floors, and the frozen final-test read remain the valid evidence.
""",
    )
    _append_once(
        notebook,
        anchor="# 12B.0 Opportunity-Conditioned Sizing, Exits, and Suppression",
        marker="Sharpe is not used for the Section 12B",
        text="""
Sharpe is not used for the Section 12B non-sequential event studies. Mean/MAD effects, date-block intervals, Validation retention, materiality bounds, and drawdown diagnostics match the stated sizing and conditioning hypotheses without pretending the overlapping events are a daily portfolio.
""",
    )
    _append_once(
        notebook,
        anchor="# GARCH Volatility Modelling",
        marker="Sharpe is not a volatility-forecast metric",
        text="""
Sharpe is not a volatility-forecast metric. GARCH conditional volatility and regime flags are evaluated as risk-state features; Sharpe becomes relevant only if a separately frozen strategy converts those forecasts into sequential returns.
""",
    )

    imports_index = _find_unique_cell(notebook, "from src.statistical_research.baselines import")
    imports_source = _source(notebook.cells[imports_index])
    performance_imports = """

from src.statistical_research.performance_diagnostics import (
    build_backtest_daily_sharpe,
    build_feature_spread_sharpe,
    build_sharpe_applicability_table,
    save_performance_diagnostics,
)
from src.statistical_research.research_figures import generate_statistical_research_figures

NOTEBOOK_FIGURE_ROOT = PROJECT_ROOT / "reports" / "figures" / "statistical_feature_research"
NOTEBOOK_FIGURE_ROOT.mkdir(parents=True, exist_ok=True)


def save_external_figure(fig: plt.Figure, relative_path: str) -> Path:
    # Save and close without embedding an inline visual in the notebook output.
    output_path = NOTEBOOK_FIGURE_ROOT / relative_path
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=180, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"Saved figure: {output_path.relative_to(PROJECT_ROOT)}")
    return output_path
"""
    if "def save_external_figure" not in imports_source:
        notebook.cells[imports_index].source = imports_source.rstrip() + performance_imports + "\n"

    replacements = [
        (
            "return_ticks = unconditional_returns.loc",
            "plt.show()",
            'save_external_figure(fig, "section05_baseline/04_return_quantiles_and_uncertainty.png")',
        ),
        (
            "range_profile = movement_summary.loc",
            "plt.show()",
            'save_external_figure(fig, "section05_baseline/05_range_and_realized_volatility.png")',
        ),
        (
            "session_key = baseline_result.session.loc",
            "fig.tight_layout(); plt.show()",
            'fig.tight_layout(); save_external_figure(fig, "section05_baseline/06_session_movement_and_availability.png")',
        ),
        (
            "tod_return = baseline_result.time_of_day.loc",
            "fig.tight_layout(); plt.show()",
            'fig.tight_layout(); save_external_figure(fig, "section05_baseline/07_time_of_day_range_heatmaps.png")',
        ),
        (
            "Visualise GARCH conditional volatility",
            "plt.show()",
            'save_external_figure(fig, "garch_volatility/25_garch_intraday_regimes.png")',
        ),
    ]
    for anchor, old, new in replacements:
        _replace_once(notebook, anchor=anchor, old=old, new=new)

    _insert_after_once(
        notebook,
        anchor="section_7_result = build_univariate_evaluation(",
        marker="## 7.3A Feature-Spread Sharpe Diagnostic",
        cells=[
            nbformat.v4.new_markdown_cell(
                """## 7.3A Feature-Spread Sharpe Diagnostic

This diagnostic asks whether the feature's Development-oriented extreme buckets produce a stable daily signed-return spread. It is computed for every evaluated engineered feature, horizon, session, and partition. Development values are in-sample diagnostics; Validation values are the honest confirmation view. Because the event returns overlap within a day and exclude costs and portfolio capacity, these values are not strategy Sharpes and cannot override the governed IC/economic-spread shortlist.
"""
            ),
            nbformat.v4.new_code_cell(
                """section_7_feature_spread_sharpe = build_feature_spread_sharpe(
    section_7_frame,
    section_7_result.cell_results,
    section_7_features,
    horizons=FORWARD_HORIZONS_MINUTES,
    sessions=EVALUATION_SESSIONS,
    partitions=EVALUATION_PARTITIONS,
    quantile_bucket_count=section_7_config.quantile_bucket_count,
    min_daily_bucket_observations=section_7_config.min_daily_observations_for_ic,
)
expected_feature_sharpe_rows = (
    len(section_7_features)
    * len(FORWARD_HORIZONS_MINUTES)
    * len(EVALUATION_SESSIONS)
    * len(EVALUATION_PARTITIONS)
)
assert len(section_7_feature_spread_sharpe) == expected_feature_sharpe_rows
assert not section_7_feature_spread_sharpe["research_partition"].eq("Final test").any()

display(
    section_7_feature_spread_sharpe.loc[
        section_7_feature_spread_sharpe["research_partition"].eq("Validation")
    ]
    .sort_values("annualized_sharpe", ascending=False)
    .head(20)
)
print(
    "Feature-spread Sharpe coverage: "
    f"{section_7_feature_spread_sharpe['feature_name'].nunique()} engineered features, "
    f"{len(section_7_feature_spread_sharpe):,} feature/session/horizon/partition cells"
)
"""
            ),
        ],
    )

    _insert_after_once(
        notebook,
        anchor="section_11_result = run_sequential_backtest(",
        marker="## 11.0A Daily Net-R Sharpe",
        cells=[
            nbformat.v4.new_markdown_cell(
                """## 11.0A Daily Net-R Sharpe

Sequential trades are summed by New York trading date in R units after scenario costs. The date index comes from the complete Section 10 candidate calendar, so zero-trade dates remain explicit rather than disappearing from the denominator. The annualized Sharpe uses 252 trading days, sample daily volatility, and zero risk-free daily R.
"""
            ),
            nbformat.v4.new_code_cell(
                """section_11_sharpe, section_11_daily_returns = build_backtest_daily_sharpe(
    section_11_result.trade_log,
    section_10_result.candidates,
    section_11_config,
)
section_11_performance_with_sharpe = section_11_result.performance.merge(
    section_11_sharpe[
        [
            "cost_scenario", "direction_variant", "gate_variant", "research_partition",
            "calendar_days", "active_days", "mean_daily_net_r", "daily_net_r_std",
            "annualized_sharpe", "total_net_r", "max_daily_drawdown_r",
        ]
    ],
    on=["cost_scenario", "direction_variant", "gate_variant", "research_partition"],
    how="left",
    validate="one_to_one",
)
assert section_11_performance_with_sharpe["annualized_sharpe"].notna().all()
display(
    section_11_performance_with_sharpe.loc[
        section_11_performance_with_sharpe["cost_scenario"].eq("base")
    ]
)
"""
            ),
        ],
    )

    performance_anchor = (
        "section_11_performance = section_11_performance_with_sharpe"
        if any(
            "section_11_performance = section_11_performance_with_sharpe" in _source(cell)
            for cell in notebook.cells
        )
        else "section_11_performance = section_11_result.performance"
    )
    performance_index = _find_unique_cell(notebook, performance_anchor)
    performance_source = _source(notebook.cells[performance_index])
    if "section_11_performance_with_sharpe" not in performance_source:
        notebook.cells[performance_index].source = performance_source.replace(
            "section_11_performance = section_11_result.performance",
            "section_11_performance = section_11_performance_with_sharpe",
            1,
        )

    _insert_after_once(
        notebook,
        anchor="GARCH feature summary:",
        marker="# 13.0 Quant Performance Review and External Figure Pack",
        cells=[
            nbformat.v4.new_markdown_cell(
                """# 13.0 Quant Performance Review and External Figure Pack

This closing audit records the Sharpe applicability decision for every research stage, persists both valid Sharpe diagnostics, and generates the external visualization pack. No figure is displayed inline. The manifest is the completeness contract for the chart suite and points to publication-quality PNG files under `reports/figures/statistical_feature_research`.
"""
            ),
            nbformat.v4.new_code_cell(
                """assert all([
    section_5_ready,
    section_6_ready,
    section_7_ready,
    section_8_ready,
    section_9_ready,
    section_10_ready,
    section_11_ready,
    section_12_ready,
    section_12b_ready,
])

sharpe_applicability = build_sharpe_applicability_table()
display(sharpe_applicability)

performance_diagnostic_save_report = save_performance_diagnostics(
    project_root=PROJECT_ROOT,
    applicability=sharpe_applicability,
    feature_spread_sharpe=section_7_feature_spread_sharpe,
    backtest_sharpe=section_11_sharpe,
    backtest_daily_returns=section_11_daily_returns,
)
assert performance_diagnostic_save_report[
    ["reload_row_match", "reload_column_match"]
].all(axis=None)
display(performance_diagnostic_save_report)

figure_manifest = generate_statistical_research_figures(
    project_root=PROJECT_ROOT,
    coverage_by_product=coverage_by_product,
    eligible_observations=eligible_observations_gc,
    horizon_availability=horizon_availability_counts,
    baseline_result=baseline_result,
    feature_registry=feature_registry_gc,
    feature_diagnostics=feature_diagnostics_gc,
    section_7_result=section_7_result,
    feature_spread_sharpe=section_7_feature_spread_sharpe,
    section_8_result=section_8_result,
    section_9_result=section_9_result,
    section_10_result=section_10_result,
    section_11_result=section_11_result,
    backtest_sharpe=section_11_sharpe,
    backtest_daily_returns=section_11_daily_returns,
    section_12_result=section_12_result,
    section_12b_result=section_12b_result,
    garch_frame=research_bars,
    garch_threshold=vol_threshold,
)
assert len(figure_manifest) == 24, figure_manifest
assert all((PROJECT_ROOT / path).is_file() for path in figure_manifest["path"])
display(figure_manifest)
print(f"External figures generated: {len(figure_manifest)}")
print(f"Figure root: {NOTEBOOK_FIGURE_ROOT.relative_to(PROJECT_ROOT)}")
print("SECTION 13 STATUS: READY")
"""
            ),
        ],
    )


def main() -> None:
    notebook = nbformat.read(NOTEBOOK_PATH, as_version=4)
    before = len(notebook.cells)
    update_notebook(notebook)
    nbformat.validate(notebook)
    nbformat.write(notebook, NOTEBOOK_PATH)
    print(f"Updated {NOTEBOOK_PATH.relative_to(PROJECT_ROOT)}: {before} -> {len(notebook.cells)} cells")


if __name__ == "__main__":
    main()
