"""Independent statistical-research utilities."""

from .labels import (
    EXPANSION_QUANTILE,
    FORWARD_HORIZONS_MINUTES,
    GC_TICK_SIZE,
    LABEL_REASON_CATEGORIES,
    ForwardLabelBuildResult,
    build_forward_label_table,
    build_label_availability_report,
    validate_tick_grid,
)
from .baselines import (
    BASELINE_RANDOM_SEED,
    BOOTSTRAP_REPLICATES,
    COST_THRESHOLDS_TICKS,
    BaselineBuildResult,
    build_baseline_outputs,
    save_baseline_outputs,
    summarize_outcomes,
)
from .feature_registry import (
    CORE_FEATURE_NAMES,
    EXPERIMENTAL_FEATURE_NAMES,
    FEATURE_NAMES,
    FEATURE_SPECS,
    FeatureSpec,
    feature_registry_frame,
    validate_registry,
)
from .feature_engineering import (
    FEATURE_SOURCE_COLUMNS,
    METADATA_COLUMNS,
    FeatureBuildResult,
    build_continuity_run_id,
    build_feature_matrix,
)
from .feature_validation import (
    FeatureSaveResult,
    build_manual_feature_audit,
    compute_feature_diagnostics,
    save_feature_outputs,
    validate_feature_matrix,
)
from .feature_evaluation import (
    EVALUATION_PARTITIONS,
    EVALUATION_SESSIONS,
    EXCLUDED_CATEGORICAL_FEATURES,
    OUTCOME_FAMILY_ATR_TEMPLATES,
    SECTION7_RANDOM_SEED,
    EvaluationBuildResult,
    Section7Config,
    benjamini_hochberg_q_values,
    build_evaluation_frame,
    build_univariate_evaluation,
    evaluated_feature_names,
    load_forward_labels_for_evaluation,
    save_evaluation_outputs,
)

__all__ = [
    "EXPANSION_QUANTILE",
    "FORWARD_HORIZONS_MINUTES",
    "GC_TICK_SIZE",
    "LABEL_REASON_CATEGORIES",
    "ForwardLabelBuildResult",
    "build_forward_label_table",
    "build_label_availability_report",
    "validate_tick_grid",
    "BASELINE_RANDOM_SEED",
    "BOOTSTRAP_REPLICATES",
    "COST_THRESHOLDS_TICKS",
    "BaselineBuildResult",
    "build_baseline_outputs",
    "save_baseline_outputs",
    "summarize_outcomes",
    "CORE_FEATURE_NAMES",
    "EXPERIMENTAL_FEATURE_NAMES",
    "FEATURE_NAMES",
    "FEATURE_SPECS",
    "FeatureSpec",
    "feature_registry_frame",
    "validate_registry",
    "FEATURE_SOURCE_COLUMNS",
    "METADATA_COLUMNS",
    "FeatureBuildResult",
    "build_continuity_run_id",
    "build_feature_matrix",
    "FeatureSaveResult",
    "build_manual_feature_audit",
    "compute_feature_diagnostics",
    "save_feature_outputs",
    "validate_feature_matrix",
    "EVALUATION_PARTITIONS",
    "EVALUATION_SESSIONS",
    "EXCLUDED_CATEGORICAL_FEATURES",
    "OUTCOME_FAMILY_ATR_TEMPLATES",
    "SECTION7_RANDOM_SEED",
    "EvaluationBuildResult",
    "Section7Config",
    "benjamini_hochberg_q_values",
    "build_evaluation_frame",
    "build_univariate_evaluation",
    "evaluated_feature_names",
    "load_forward_labels_for_evaluation",
    "save_evaluation_outputs",
]
